import Buttons from "../Buttons/Buttons";

export default function Pricing() {
  return (
    <div>
      <h2>Our Pricing</h2>
      {/* <ul>
        <li>
          <h3></h3>
          <p></p>
          <p></p>
          <h4></h4>
          <p></p>
          <h4></h4>
          <ul>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
          </ul>
        </li>
        <li>
          <h3></h3>
          <p></p>
          <p></p>
          <h4></h4>
          <p></p>
          <h4></h4>
          <ul>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
          </ul>
        </li>
        <li>
          <h3></h3>
          <p></p>
          <p></p>
          <h4></h4>
          <p></p>
          <h4></h4>
          <ul>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
          </ul>
        </li>
        <li>
          <h3></h3>
          <p></p>
          <p></p>
          <h4></h4>
          <p></p>
          <h4></h4>
          <ul>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
            <li>
              <p>
                <span></span>
              </p>
            </li>
          </ul>
        </li>
      </ul> */}
      <Buttons>Get a Quote</Buttons>
    </div>
  );
}
